# Generated by Django 5.2.1 on 2025-08-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindlogs', '0006_mindlog_total_views'),
        ('myapp', '0112_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindlog',
            name='latency',
        ),
        migrations.RemoveField(
            model_name='mindlog',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='mindlog',
            name='neuro_color',
        ),
        migrations.RemoveField(
            model_name='mindlog',
            name='total_views',
        ),
        migrations.AddField(
            model_name='mindlog',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_logs_comments', to='myapp.userinfo')),
                ('mindlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mindlogs.mindlog')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mindlogs.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindlog_comments', to='myapp.userinfo')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['mindlog', 'timestamp'], name='mindlogs_co_mindlog_0b420e_idx'), models.Index(fields=['user', 'timestamp'], name='mindlogs_co_user_id_e9fdb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Like'), ('🔥', 'Fire'), ('🚀', 'Ship It'), ('❤️', 'Love'), ('💡', 'Insight'), ('🐛', 'Bug')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mindlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='mindlogs.mindlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindlog_reactions', to='myapp.userinfo')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mindlog', 'emoji'], name='mindlogs_re_mindlog_684103_idx'), models.Index(fields=['user', 'timestamp'], name='mindlogs_re_user_id_c30513_idx')],
                'unique_together': {('mindlog', 'user')},
            },
        ),
    ]
