# Generated by Django 5.2.1 on 2025-11-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0113_remove_saveditem_events_remove_event_comment_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_project',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='user_project',
            name='user',
        ),
        migrations.DeleteModel(
            name='current_position',
        ),
        migrations.DeleteModel(
            name='user_project',
        ),
    ]
