# Generated by Django 5.2.1 on 2025-11-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0114_remove_user_project_tech_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_views',
        ),
    ]
