# Generated by Django 5.2.1 on 2025-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0115_remove_userinfo_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post_comments',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='post_comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_comment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Started following you')], max_length=60),
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='post_comments',
        ),
    ]
