# Generated by Django 5.2.1 on 2025-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0116_remove_notification_post_remove_post_comments_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='banner_image',
            field=models.CharField(blank=True, default='banners/default.jpg', max_length=255, null=True),
        ),
    ]
