# Generated by Django 5.2.1 on 2025-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0117_userinfo_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for displaying dates/times", max_length=63),
        ),
    ]
