# Generated by Django 5.2.1 on 2025-11-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0118_userinfo_timezone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CringeBadge',
            new_name='CodingStyle',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='cringe_badge',
            new_name='coding_style',
        ),
    ]
