# Generated by Django 5.2.1 on 2025-11-26 15:01

from django.db import migrations


def populate_coding_styles(apps, schema_editor):
    """Populate the CodingStyle model with predefined coding personalities"""
    CodingStyle = apps.get_model('myapp', 'CodingStyle')
    
    coding_styles = [
        {
            'name': 'Coffee Coder',
            'emoji': '☕',
            'description': 'My code is 60% caffeine, 40% logic. ☕\nMy brain boots up only after the first sip, and by the second cup I\'m basically a high-performance compiler. Mornings are my golden hour, and if you want clean code? Catch me before noon, mug in hand.'
        },
        {
            'name': 'Debug Duck',
            'emoji': '🦆',
            'description': 'I talk through every bug like it\'s a podcast no one asked for. 🦆\nIf you hear me mumbling at my desk, don\'t worry — I\'m negotiating with my code. Explaining it out loud magically makes the solution appear (or at least makes the duck proud).'
        },
        {
            'name': 'Terminal Samurai',
            'emoji': '⚔️',
            'description': '⚔️ Terminal is life. I live in the command line and barely touch the mouse. I automate everything because clicking is for normies. Linux, bash scripts, and DevOps stuff make me happy.'
        },
        {
            'name': 'Zen Refactorer',
            'emoji': '🧘',
            'description': 'I chase inner peace through cleaner code. 🧘\nGive me a messy function and I\'ll turn it into poetry. Shipping is cool, but shipping something elegant? That\'s enlightenment. My pull requests come with fewer lines and a calmer soul.'
        },
        {
            'name': 'Error Collector',
            'emoji': '🐛',
            'description': 'I learn by breaking things — proudly. 🐛\nNothing teaches faster than a bug that refuses to die. I roll updates like dice: sometimes I fix it, sometimes I create three new issues, and that\'s okay. Every error log is XP.'
        },
        {
            'name': 'Night Owl',
            'emoji': '🌙',
            'description': 'My productivity peaks when the world is asleep. 🌙\n2 AM? Perfect time to redesign an architecture or start a brand-new side project. The darkness gives me +10 focus and -100 self-control. Tomorrow me will deal with whatever I coded tonight.'
        },
        {
            'name': 'Precision Sprinter',
            'emoji': '🎯',
            'description': 'I ship faster than my tests can run. 🎯\n\'Move fast and break things\' isn\'t a motto — it\'s a personality trait. Deadlines are my adrenaline. I\'ll get it done today, and I\'ll optimize it tomorrow… or next week… maybe.'
        },
        {
            'name': 'Team Player',
            'emoji': '🤝',
            'description': 'I level up around people. 🤝\nPut me in a room with other devs and suddenly I have ideas, jokes, and questionable metaphors. I thrive on code reviews, planning sessions, and collective \'aha!\' moments. Building together just hits different.'
        }
    ]
    
    for style_data in coding_styles:
        CodingStyle.objects.get_or_create(
            name=style_data['name'],
            defaults={
                'emoji': style_data['emoji'],
                'description': style_data['description']
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0119_rename_cringe_badge_to_coding_style'),
    ]

    operations = [
        migrations.RunPython(populate_coding_styles),
    ]
