# Generated by Django 5.2.1 on 2025-11-26 15:01

from django.db import migrations


def populate_coding_styles(apps, schema_editor):
    """
    DEPRECATED: This migration originally populated CodingStyle data.
    
    Data seeding has been disabled to allow exclusive management via Django admin.
    All coding styles should now be created and updated through the admin panel.
    """
    pass  # No-op: Do not seed data via migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0119_rename_cringe_badge_to_coding_style'),
    ]

    operations = [
        migrations.RunPython(populate_coding_styles, reverse_code=migrations.RunPython.noop),
    ]
