# Generated by Django 5.2.1 on 2025-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0120_populate_coding_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingstyle',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
