# Generated by Django 5.2.1 on 2025-11-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0122_auto_20251127_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingstyle',
            name='emoji',
        ),
    ]
