# Generated by Django 5.2.1 on 2025-11-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0123_remove_codingstyle_emoji'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
