# Generated by Django 5.2.1 on 2025-11-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0124_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='domains',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
