# Generated by Django 5.2.1 on 2025-12-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0131_alter_userinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When coordinates were last updated', null=True),
        ),
    ]
