# Generated by Django 6.0 on 2025-12-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0133_separate_geolocation_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='location_browser_updated_at',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='location_ip_updated_at',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='browser_latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='browser_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When browser GPS location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='browser_longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='browser_permission_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('denied', 'Denied')], default='unknown', help_text='Browser geolocation permission status', max_length=10),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip_latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When IP-based location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip_longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
