# Generated by Django 5.2.1 on 2025-12-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0134_mvp_geolocation_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ip_latitude',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ip_location_updated_at',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ip_longitude',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='browser_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When browser location was last updated', null=True),
        ),
    ]
