# Generated by Django 5.2.1 on 2025-06-22 12:33

import django.db.models.deletion
import logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0112_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('neuro_color', models.CharField(default='green', max_length=20)),
                ('latency', models.PositiveIntegerField(default=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sig', models.CharField(default=logs.models.generate_unique_signature, max_length=20, unique=True)),
                ('clone_count', models.PositiveIntegerField(default=0)),
                ('original_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='logs.mindlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_logs', to='myapp.userinfo')),
            ],
        ),
    ]
