# Generated by Django 5.2.1 on 2025-06-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindlog',
            name='neuro_color',
            field=models.CharField(blank=True, default='green', max_length=20, null=True),
        ),
    ]
