# Generated by Django 5.2.1 on 2025-07-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_mindlog_neuro_color'),
        ('myapp', '0112_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindlog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_logs', to='myapp.userinfo'),
        ),
    ]
