# Generated by Django 5.2.1 on 2025-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_mindlog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindlog',
            name='code_snippet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mindlog',
            name='snap_shot',
            field=models.ImageField(blank=True, null=True, upload_to='log_snap_shot'),
        ),
    ]
