# Generated by Django 5.2.1 on 2025-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_mindlog_code_snippet_mindlog_snap_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindlog',
            name='code_snippet',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
