# Generated by Django 5.2.1 on 2025-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_mindlog_code_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindlog',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
