# Generated by Django 5.2.1 on 2025-11-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_remove_mindlog_latency_remove_mindlog_likes_and_more'),
        ('myapp', '0113_remove_saveditem_events_remove_event_comment_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MindLog',
            new_name='Log',
        ),
    ]
