# Generated by Django 5.2.1 on 2025-11-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_rename_mindlog_log'),
    ]

    def update_app_label(apps, schema_editor):
        # Update ContentType app_label from 'mindlogs' to 'logs'
        ContentType = apps.get_model('contenttypes', 'ContentType')
        ContentType.objects.filter(app_label='mindlogs').update(app_label='logs')

    operations = [
        migrations.RunPython(update_app_label, reverse_code=migrations.RunPython.noop),
    ]
