# Generated by Django 5.2.1 on 2025-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_update_contenttype'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='logs_commen_mindlog_16ccb4_idx',
            old_name='mindlogs_co_mindlog_0b420e_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='logs_commen_user_id_0d4441_idx',
            old_name='mindlogs_co_user_id_e9fdb6_idx',
        ),
        migrations.RenameIndex(
            model_name='reaction',
            new_name='logs_reacti_mindlog_656e75_idx',
            old_name='mindlogs_re_mindlog_684103_idx',
        ),
        migrations.RenameIndex(
            model_name='reaction',
            new_name='logs_reacti_user_id_905b99_idx',
            old_name='mindlogs_re_user_id_c30513_idx',
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
