# Generated by Django 5.2.1 on 2025-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_rename_mindlogs_co_mindlog_0b420e_idx_logs_commen_mindlog_16ccb4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='code_snippet',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
