# Generated by Django 5.2.1 on 2025-11-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_log_code_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='clone_count',
        ),
        migrations.RemoveField(
            model_name='log',
            name='original_log',
        ),
    ]
