# Generated by Django 5.2.1 on 2025-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_remove_clone_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('❤️', 'Like'), ('🚀', 'Rocket'), ('💡', 'Insight'), ('😢', 'Sad')], max_length=10),
        ),
    ]
