# Generated by Django 5.2.1 on 2025-11-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_rename_cringe_badge_to_coding_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
    ]
