# Generated by Django 5.2.1 on 2025-11-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('logs', '0014_alter_comment_options'),
        ('myapp', '0124_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('target_object_id', models.PositiveIntegerField()),
                ('action_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('follow', 'New Follower'), ('comment', 'New Comment'), ('reply', 'Comment Reply'), ('reaction', 'Reaction'), ('mention', 'Mentioned in Log'), ('comment_mention', 'Mentioned in Comment')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_actions', to='contenttypes.contenttype')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to='myapp.userinfo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.userinfo')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-timestamp'], name='logs_notifi_recipie_199624_idx'), models.Index(fields=['recipient', 'notification_type'], name='logs_notifi_recipie_2bf11a_idx'), models.Index(fields=['recipient', '-timestamp'], name='logs_notifi_recipie_885baf_idx')],
            },
        ),
    ]
