# Generated by Django 5.2.1 on 2025-12-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_alter_log_code_snippet'),
        ('myapp', '0129_alter_userinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='logs.log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_views', to='myapp.userinfo')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='logs_logvie_user_id_26f5a5_idx'), models.Index(fields=['user', 'log'], name='logs_logvie_user_id_611fb3_idx')],
                'unique_together': {('user', 'log')},
            },
        ),
    ]
