# Generated by Django 6.0 on 2025-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_logviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(max_length=280),
        ),
    ]
