# Generated by Django 5.2.1 on 2025-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_alter_log_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_text', models.CharField(default='What are you working on?', help_text='Placeholder text shown in the log content field', max_length=200)),
            ],
            options={
                'verbose_name': 'Log Form Settings',
                'verbose_name_plural': 'Log Form Settings',
            },
        ),
    ]
